# name: Build

# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     container: ghcr.io/yotona/twewy-build:latest

#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         version: [usa]

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           submodules: recursive

#       - name: Prepare
#         run: |
#           mv /extract/* ./extract
#           mv ./extract/arm7_bios.bin .

#       - name: Download dsd
#         run: |
#           python tools/download_tool.py dsd v0.9.1 --path dsd

#       - name: Download objdiff
#         run: |
#           python tools/download_tool.py objdiff v2.7.1 --path objdiff-cli

#       - name: Download wibo
#         run: |
#           python tools/download_tool.py wibo 0.6.16 --path wibo

#       - name: Build
#         run: |
#           python tools/configure.py --version ${{ matrix.version }} -w wibo --compiler /mwccarm --no-extract
#           ninja

#       - name: Upload report
#         uses: actions/upload-artifact@v4
#         with:
#           name: ${{ matrix.version }}_report
#           path: build/${{ matrix.version }}/report.json